she_codes_news/news/urls.py
# news/urls.py
from django.urls import path
from . import views

app_name = 'news'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.StoryView.as_view(), name='story'),
    path('add-story/', views.AddStoryView.as_view(), name='newsStory'),
    path('news/add_comment/<int:pk>', views.AddCommentView.as_view(), name='add_comment')
]

she_codes_news/she_codes_news/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('news/', include('news.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
]

she_codes_news/users/urls.py
# users/urls.py
from django.urls import path
from .views import CreateAccountView,UserProfileView


app_name ='users'

urlpatterns = [
    path('create-account/', CreateAccountView.as_view(), name='createAccount'),
    path('profile/', UserProfileView.as_view(), name='userProfile'),
]

she_codes_news/news/models.py
from datetime import datetime
from django.db import models
from django.contrib.auth import get_user_model



class NewsStory(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE
    )
    image = models.URLField(max_length=200, null=True)
    pub_date = models.DateTimeField()
    content = models.TextField()

# Comment code:

class Comment(models.Model):
    post = models.ForeignKey('news.NewsStory', on_delete=models.CASCADE, related_name='comments')
    author = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=datetime.now)
    approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.approved_comment = True
        self.save()

    def __str__(self):
        return self.text

she_codes_news/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    bio = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.username

she_codes_news/news/forms.py
# news/forms.py

from django import forms
from django.forms import ModelForm, ValidationError
from .models import NewsStory, Comment


class StoryForm(ModelForm):
    class Meta:
        model = NewsStory
        fields = ['title', 'image', 'pub_date', 'content']
        widgets = {
            'pub_date': forms.DateInput(
                format='%m/%d/%Y',
                attrs={
                    'class':'form-control',
                    'placeholder':'Select a date',
                    'type':'date'
                }
            ),
        }

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ('author', 'text')


    def clean_text(self):
        text = self.cleaned_data['text']
        if len(text) < 10:
            raise ValidationError('Comment must be at least 10 characters long.')
        return text

she_codes_news/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser

#this form below creates a new user, so you can add more fields in the list below if needed

class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = CustomUser
        fields = ['username', 'email']
    
#this form below adds custom fields for the user to fill, so you can add more fields in the list below if needed


class CustomUserChangeForm(UserChangeForm):
    
    class Meta:
        model = CustomUser
        fields = ['username', 'email', 'bio']
        

she_codes_news/news/views.py
from django.views import View
from django.views import generic
from django.urls import reverse_lazy
from .models import NewsStory
from .forms import CommentForm, StoryForm
from django.views.generic.edit import FormView
from django.shortcuts import render, redirect, get_object_or_404



class IndexView(generic.ListView):
    template_name = 'news/index.html'
    context_object_name = "all_stories"

    def get_queryset(self):
        '''Return all news stories.'''
        return NewsStory.objects.all().order_by("-pub_date", "title")
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['latest_stories'] = NewsStory.objects.order_by("-pub_date", "title").all()[:4]
        context['all_stories'] = NewsStory.objects.order_by("-pub_date", "title")
        #print(NewsStory.objects.all()[:4])
        return context


class StoryView(generic.DetailView):
    model = NewsStory
    template_name = 'news/story.html'
    context_object_name = 'story'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        story = self.get_object()
        # Order comments by their created_date in descending order (most recent first)
        context['comments'] = story.comments.filter(approved_comment=True).order_by('-created_date')
        context['form'] = CommentForm()
        return context


class AddStoryView(generic.CreateView):
    form_class = StoryForm
    context_object_name = 'storyform'
    template_name = 'news/createStory.html'
    success_url = reverse_lazy('news:index')

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


def get_success_url(self):
    '''Get the success URL for the form.'''
    news_story = self.get_object()
    return reverse_lazy('news:story', kwargs={'pk': news_story.pk})


class AddCommentView(View):
    def post(self, request, pk):
        news_story = get_object_or_404(NewsStory, pk=pk)
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = news_story
            comment.save()
        
        # Get the updated list of comments for the story
        comments = news_story.comments.filter(approved_comment=True)

        # Pass the updated list of comments to the template
        return render(request, 'news/story.html', {'story': news_story, 'comments': comments})

    def get_object(self):
        """Get the news story that the comment is being added to."""
        news_story_pk = self.kwargs['pk']
        return NewsStory.objects.get(pk=news_story_pk)

she_codes_news/users/views.py
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from django.views import generic
from django.views import View
from .models import CustomUser
from .forms import CustomUserCreationForm
from django.shortcuts import render, redirect


class CreateAccountView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'users/createAccount.html'
#this part above takes you back to the login page after you've created an account, with most websites, this is automated in the background so once you create the account, you don't need to login again --- this could be something we change on our website if we wanted so you're not having to login again

class UserProfileView(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'users/userprofile.html', {'user': request.user})
    
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('users:login')
        return super().dispatch(request, *args, **kwargs)

she_codes_news/news/templates/news/createStory.html
{% extends "base.html"%}

{% block content %}

    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Post my story!">
    </form>

{% endblock %}

she_codes_news/news/templates/news/index.html
{% extends "base.html" %}
{% load static %}

{% block stylesheets %}
    <link rel="stylesheet" type="text/css" href="{% static 'news/styles.css'%}">
{% endblock %}

{% block content %}

    <br>
    <a href="{% url 'news:newsStory' %}">Ready to write your Own Story?</a>



    <h2>Latest Stories!</h2>

    <div id="latest-stories">
        {% if latest_stories %}
            {% for story in latest_stories %}
                {% include "./storyCard.html" with story=story position=forloop.counter %}
            {% endfor %}
        {% else %}
            <p>No stories are available.</p>
        {% endif %}
    </div>

    <div id="all-stories">
        {% if latest_stories %}
            {% for story in all_stories %}
                {% include "./storyCard.html" with story=story %}
            {% endfor %}
        {% else %}
            <p>No stories are available.</p>
        {% endif %}
    </div>



{% endblock %}

she_codes_news/news/templates/news/story.html
<!-- news/templates/news/story.html -->
{% extends "base.html" %}
{% load static %}

{% block stylesheets %}
    <link rel="stylesheet" type="text/css" href="{% static 'news/styles.css'%}">
{% endblock %}

{% block content %}

    <div id="story-wrapper">
        <h2>{{ story.title }}</h2>
        <h4>{{ story.author }}</h4>
        <div id="story-content">
            <img src="{% static '/news/images/img-2.jpg' %}">
            {{ story.content|linebreaks }}
        </div>
    </div>

    {% if comments %}
        <h2>Comments</h2>
        <ul>
            {% for comment in comments %}
                <li>
                    <strong>{{ comment.author }}</strong>: {{ comment.text }}
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No comments here, yet. Why not be the first?</p>
    {% endif %}

    <h2>Have your say!</h2>
    {% if user.is_authenticated %}
        <form action="{% url 'news:add_comment' pk=story.pk %}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Add Comment" />
        </form>
    {% else %}
        <p>Please <a href="{% url 'login' %}">login</a> to have your say.</p>
    {% endif %}

{% endblock %}

she_codes_news/news/templates/news/storyCard.html
<div class="story-card" id="story-card-{{ position }}">
    <a href="{% url 'news:story' story.id %}">
        {% if position < 5 %}
            {% if story.image is None %}
                <img src="../static/news/images/img-{{ position }}.jpg">
            {% else %}
                <img src={{ story.image }}>
            {% endif %}
        {% else %}
        <img src={{ story.image }}>
        {% endif %}
        
        <div class="story-card-text">
            <h3>{{ story.title }}</h3>
            <h4>{{ story.author }}</h4>
            <h4>{{ story.pub_date }}</h4>
        </div>
    </a>
</div>

she_codes_news/templates/base.html
{% load static %}

<!doctype html>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>She Codes News</title>
        <meta name="description" content="">
        <meta name="author" content="Pauline Segi">
        <link href="https://fonts.googleapis.com/css?family=Manjari&display=swap" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
        {% block stylesheets %} {% endblock %}
    </head>

    <body>
        <header>
            <div id="header-text">
                <a id="header-link" href="{% url 'news:index' %}">
                    <h1>She {Codes} News</h1>
                </a>
            </div>
            {% include './nav.html' %}
        </header>

        {% block content %} {% endblock %}
    </body>
</html>

she_codes_news/templates/nav.html
<nav>
    <a href="{% url 'news:index' %}">Home</a>
    {% if request.user.is_authenticated %}
    <a href="{% url 'users:userProfile' %}">{{ user.username }}</a>    
    <a href="{% url 'logout' %}">Logout</a>
    {% else %}
        <a href="{% url 'login' %}">Login</a>
    {% endif %}
</nav>

she_codes_news/users/templates/users/createAccount.html
<!-- users/templates/users/createAccount.html -->
{% extends 'base.html' %}

{% block content %}
    <h2>Create an Account</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Let's get started!</button>
    </form>
{% endblock %}

she_codes_news/users/templates/users/userprofile.html
{% block content %}
  <h1>My Profile</h1>
  {% if request.user.is_authenticated %}
    <p>Username: {{ user.username }}</p>
    <p>Email: {{ user.email }}</p>
  {% else %}
    <p>You are not logged in.</p>
  {% endif %}
{% endblock %}